apps/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.BlogIndex.as_view(), name='index'),
]

apps/core/urls.py
from os import name
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.Index.as_view(),name='index'),
    path('passport-info/', views.Passport.as_view(), name='passport-info'),
    path('passport-info-display/<str:pk>', views.PassportInfo.as_view(), name='passport-info-display'),
    path('members-list/', views.MembersList.as_view(), name='member-list'),
    path('download/list', views.download_members_list, name='download-list')
]

esn/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from apps.coming_soon.views import SoonView
import apps.core.views

handler404 = apps.core.views.handler404
handler500 = apps.core.views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.core.urls')),
    path('blog/', include('apps.blog.urls')),
]

if settings.DEBUG:
    media_url = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += media_url

apps/core/models.py
from django.db import models
import logging
from io import BytesIO
from PIL import Image
from django.core.files.base import ContentFile

logger = logging.getLogger(__name__)

class ImageCompressMixin:
    """
    Mixin to compress models
    `ImageField`
    """

    def _compress_img(self, img, quality=20, format='JPEG'):
        """
        Function helps in the reduction of image
        quality
        """
        logger.info("Compressing image")
        img = Image.open(img)
        compressed_img = BytesIO()
        img.save(compressed_img, quality=quality, format=format)
        compressed_img.seek(0)
        return compressed_img

    def compress_img(self, field):
        """
        Compresses the image of the
        field specified
        """
        compressed = self._compress_img(img=field)
        field.save(
                field.name,
                ContentFile(compressed.read()),
                save=False,
            )
        compressed.close()


class Site(models.Model):
    """
    This model holds the sites information
    """
    name = models.CharField(max_length=200, )
    domain = models.URLField(blank=True)
    about = models.TextField()
    mission = models.TextField()
    vision = models.TextField()
    favicon = models.ImageField()
    appleicon = models.ImageField()
    logo = models.ImageField()
    email = models.EmailField()
    address = models.TextField()

    def __str__(self):
        return self.name


class PhoneNumber(models.Model):
    site = models.ForeignKey(
        Site, related_name='numbers', on_delete=models.CASCADE)
    # Note: if it is ineffective to store numbers in the format 080-xxx
    number = models.IntegerField()
    # i'll have to change the field type to `models.CharField`

    def __str__(self) -> str:
        return self.site.name


class Event(models.Model):
    """
    This models stores info all events
    """
    OPTIONS = (
        ('meeting', 'Meeting'),
        ('workshop', 'Workshop'),
        ('seminar', 'Seminar'),
    )
    title = models.CharField(max_length=200)
    poster = models.ImageField()
    location = models.CharField(max_length=200)
    date_time = models.DateTimeField()
    duration = models.DurationField(blank=True)
    info = models.TextField(help_text="more helpful informations...")

    def __str__(self) -> str:
        return self.title


class FAQ(models.Model):
    """
    This model stores all Frequently Asked Questions
    """
    site = models.ForeignKey(
        Site, related_name='faqs', on_delete=models.CASCADE)
    question = models.CharField(max_length=200)
    answer = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.question


class TeamLead(models.Model):
    """
    This model stores all infomations about each team leads
    """
    site = models.ForeignKey(
        Site, related_name='team_leads', on_delete=models.CASCADE)
    fullname = models.CharField(max_length=60)
    title = models.CharField(max_length=100, help_text='position occupied')
    photo = models.ImageField()
    blockquote = models.TextField(
        help_text="your favourite quote or whatever you feel...")

    def __str__(self) -> str:
        return self.fullname


class SocialAccount(models.Model):
    OPTIONS = (
        ('facebook', 'Facebook'),
        ('instagram', 'Instagram'),
        ('linkedin', 'LinkedIn'),
        ('twitter', 'Twitter'),
    )
    name = models.CharField(max_length=20, choices=OPTIONS)
    url = models.URLField()

    def __str__(self) -> str:
        return self.name


class SiteSocialAccount(SocialAccount):
    site = models.ForeignKey(
        Site, related_name='social_accounts', on_delete=models.CASCADE)


class TeamLeadSocialAccount(SocialAccount):
    site = models.ForeignKey(
        TeamLead, related_name='social_accounts', on_delete=models.CASCADE)


class Member(ImageCompressMixin, models.Model):
    """
    This models stores the members info for the 
    passport.
    """
    DEPARTMENT_OPTIONS = (
        ('civil engr', 'Civil Engineering'),
        ('mech engr', 'Mechanical Engineering'),
        ('elect engr', 'Electrical Engineering'),
        ('Computer engr', 'Computer Engineering'),
    )
    TEAM_OPTIONS = (
        ('0','Media Team'),
        ('1', 'Research Team'),
        ('2', 'Logistics Team'),
        ('3','Project Supervision Team'),
        ('4', 'Finance Team'),
        ('5', 'Departmental Team'),
        ('6','Design and Creative Team'),
        ('7','Purchase Team'),
        ('8', 'Organizing Team'),
        ('9', 'Project Team'),
        ('10', 'Campus Team'),
    )
    
    lastname = models.CharField(
        max_length=100, help_text='Your surname')
    firstname = models.CharField(
        max_length=100, help_text='Your name')
    othername = models.CharField(
        max_length=100, help_text="Your middle name"
    )
    department = models.CharField(max_length=50, choices=DEPARTMENT_OPTIONS)
    phone_number1 = models.CharField(max_length=15, blank=True, default='Nil')
    phone_number2 = models.CharField(max_length=15, blank=True, default='Nil', help_text="*optional")
    position = models.CharField(max_length=50, default='Nil')
    team = models.CharField(max_length=30, choices=TEAM_OPTIONS)
    passport = models.ImageField(help_text='Strictly your pasport photograph on a white background')

    def __str__(self) -> str:
        return  self.get_fullname()

    def get_fullname(self):
        return f"{self.lastname} {self.firstname} {self.othername}".title()

    def join_numbers(self):
        if self.phone_number1 =='Nil' and self.phone_number2 =='Nil':
            return 'Nil'
        elif self.phone_number1 !='Nil' and self.phone_number2 =='Nil':
            return self.phone_number1
        return " ,".join([self.phone_number1,self.phone_number2])

apps/core/forms.py
from django import forms
from django.forms import fields
from . import models

class PassportForm(forms.ModelForm):
    class Meta:
        model = models.Member
        fields = '__all__'

apps/core/views.py
import django
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import TemplateView
from django.views import View
from django.views.generic.edit import FormView
from django.contrib import messages
from . import forms, models
import logging
from openpyxl import Workbook
from django.conf import settings
import tempfile
from io import BytesIO

logger = logging.getLogger(__name__)

# Create your views here.


class Index(TemplateView):
    template_name = 'core/index.html'


class Passport(FormView):
    template_name = 'core/passport-form.html'
    form_class = forms.PassportForm

    def __init__(self, *args, **kwargs):
        self.member = None
        super().__init__(**kwargs)

    def form_valid(self, form: forms.PassportForm):
        member = form.save()
        messages.success(
            self.request, 'Your information was successfully uploaded')
        return redirect(reverse('core:passport-info-display', kwargs={'pk': member.pk}))

    def form_invalid(self, form):
        messages.error(self.request, "An error occured. please try again")
        return super().form_invalid(form)


class PassportInfo(View):
    def get(self, request, pk):
        member = models.Member.objects.get(pk=pk)
        return render(request, 'core/passport-form.html', {'member': member})


class MembersList(TemplateView):
    template_name = 'core/members-list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        members = models.Member.objects.all()
        context['members'] = sorted(members, key=lambda m: m.get_fullname())
        return context


def download_members_list(request):
    members_list = sorted(models.Member.objects.all(),
                          key=lambda m: m.get_fullname())
    members = [(
        idx + 1,
        member.lastname.upper(),
        member.firstname.upper(),
        member.othername.upper(),
        member.join_numbers(),
        member.position.upper(),
        member.get_team_display().upper(),
        member.passport.url) for idx, member in enumerate(members_list)]
    logger.debug(members)
    if request.GET.get("format") == "xlsx":
        wb=Workbook()
        sheet=wb.active
        sheet.title='Bio-Data'
        headers=['S/N',
                   'Lastname',
                   'Firstname',
                   'Othername',
                   'Phone Number',
                   'Position',
                   'Team',
                   'Passport']  # Headers if names are required to be discrete.
        headers_name_merged=['S/N',
                   'Fullname',
                   'Phone Number',
                   'Position',
                   'Team',
                   'Passport']  # Headers if names are required to be merged.

        # Logic to loop through `headers_name_merged` and `members_name_merged`
        if request.GET.get("names") == "merged":
            members_name_merged=[(
        idx + 1,
        member.get_fullname().upper(),
        member.join_numbers(),
        member.position.upper(),
        member.get_team_display().upper(),
        member.passport.url) for idx, member in enumerate(members_list)]
            # to populate the excel sheet.
            for index, row in enumerate(sheet.iter_rows(min_row=1, max_col=6, max_row=len(members_name_merged) + 1)):
                if index == 0:
                    for idx, cell in enumerate(row):
                        cell.value=headers_name_merged[idx]

            for row in range(2, len(members_name_merged) + 2):
                for idx, col in enumerate(headers_name_merged):
                    sheet.cell(row=row, column=idx+1,
                               value=members_name_merged[row-2][idx])

        else:  # alternate logic if names are required to be discrete.
            for index, row in enumerate(sheet.iter_rows(min_row=1, max_col=8, max_row=len(members) + 1)):
                if index == 0:
                    for idx, cell in enumerate(row):
                        cell.value=headers[idx]

            for row in range(2, len(members) + 2):
                for idx, col in enumerate(headers):
                    sheet.cell(row=row, column=idx+1,
                               value=members[row-2][idx])

        # saving the file
        temp_file=BytesIO()
        wb.save(filename=temp_file)
        temp_file.seek(0)

        response=HttpResponse(
            content_type="application/vnd.ms-excel"
        )
        name = models.Site.objects.first().name
        response["Content-Disposition"]=f"inline; filename={name}-members-bio-data.xlsx"
        response["Content-Transfer-Encoding"]="binary"
        response.write(temp_file.read())
        temp_file.close()
        return response


def handler404(request, exception):
    logger.error("Could not resolve path: ", str(exception.get('path')))
    return render(request, 'core/404.html')


def handler500(request):
    return render(request, 'core/500.html')

apps/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>{% block title %}{% endblock %}</title>
  <meta content="" name="description">

  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'core/img/favicon.png' %}" rel="icon">
  <link href="{% static 'core/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'core/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
  <link href="{% static 'core/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'core/css/style.css' %}" rel="stylesheet">

  <!-- =======================================================
  * Template Name: FlexStart - v1.7.0
  * Template URL: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
  <style>
    .fix-overlay{
      white-space: normal;
    }
  </style>
  {% block head %}{% endblock %}
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'core:index' %}" class="logo d-flex align-items-center">
        {% if site.logo %}<img src="{{ site.logo.url }}" alt="">{% endif %}
        <span></span>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% if request.path == '/' %}#hero{% else %}{% url 'core:index' %}#hero{% endif %}">Home</a></li>
          <li><a class="nav-link scrollto" href="{% if request.path == '/' %}#about{% else %}{% url 'core:index' %}#about{% endif %}">About</a></li>
          <li><a class="nav-link scrollto" href="{% if request.path == '/' %}#team{% else %}{% url 'core:index' %}#team{% endif %}">Team</a></li>
          <li><a href="{% url 'blog:index' %}">Blog</a></li>
          <li class="dropdown"><a href="#"><span>More</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Gallery</a></li>
              <li class="dropdown"><a href="#"><span>Resources</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Audios</a></li>
                  <li><a href="#">Videos</a></li>
                  <li><a href="#">Documents</a></li>
                </ul>
              </li>
              <li><a href="#">EEPs</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="{% if request.path == '/' %}#contact{% else %}{% url 'core:index' %}#contact{% endif %}">Contact</a></li>
          <li><a class="getstarted scrollto" href="{% if request.path == '/' %}#{% else %}{% url 'core:index' %}{% endif %}">Sign up</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  {% block container %}
  {% endblock %}

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12 text-center">
            <h4>Our Newsletters</h4>
            <p>Subscribe to personalised newsletters from us, we promise not to spam</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="index.html" class="logo d-flex align-items-center">
              {% if site.logo %}<img src="{{ site.logo.url }}" alt="">{% endif %}
              <span class="fix-overlay"></span>
            </a>
            <h3>{{ site.name }}</h3>
            <p>{{ site.about }}</p>
            <div class="social-links mt-3">
              {% for account in site.social_accounts.all %}
              <a href="{{ account.url }}" class="{{ account.name }}" target="_blank"><i class="bi bi-{{ account.name }}"></i></a>
              {% endfor %}
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Blog</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>
              {{ site.address }} <br><br>
              {% for number in site.numbers.all %}
              <strong>Phone:</strong> <a href="tel:{{ number.number }}">{{ number.number }}</a><br>
              {% endfor %}
              <strong>Email:</strong> <a href="mailto:{{ site.email }}">{{ site.email }}</a><br>
            </p>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>{{ site.name }}</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
        Template by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
      <div class="credits">
        Designed by <a href="#">{{ site.name }} Media Team</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'core/vendor/bootstrap/js/bootstrap.bundle.js' %}"></script>
  <script src="{% static 'core/vendor/aos/aos.js' %}"></script>
  <!-- <script src="core/vendor/php-email-form/validate.js"></script> -->
  <script src="{% static 'core/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'core/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'core/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'core/vendor/glightbox/js/glightbox.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'core/js/main.js' %}"></script>

</body>

</html>

apps/core/templates/core/inner-page.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Inner Page - FlexStart Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="assets/img/favicon.png" rel="icon">
  <link href="assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="assets/vendor/aos/aos.css" rel="stylesheet">
  <link href="assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
  <link href="assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: FlexStart - v1.7.0
  * Template URL: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="index.html" class="logo d-flex align-items-center">
        <img src="assets/img/logo.png" alt="">
        <span>FlexStart</span>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto " href="#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="#about">About</a></li>
          <li><a class="nav-link scrollto" href="#services">Services</a></li>
          <li><a class="nav-link scrollto" href="#portfolio">Portfolio</a></li>
          <li><a class="nav-link scrollto" href="#team">Team</a></li>
          <li><a href="blog.html">Blog</a></li>
          <li class="dropdown"><a href="#"><span>Drop Down</span> <i class="bi bi-chevron-down"></i></a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li class="dropdown"><a href="#"><span>Deep Drop Down</span> <i class="bi bi-chevron-right"></i></a>
                <ul>
                  <li><a href="#">Deep Drop Down 1</a></li>
                  <li><a href="#">Deep Drop Down 2</a></li>
                  <li><a href="#">Deep Drop Down 3</a></li>
                  <li><a href="#">Deep Drop Down 4</a></li>
                  <li><a href="#">Deep Drop Down 5</a></li>
                </ul>
              </li>
              <li><a href="#">Drop Down 2</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
            </ul>
          </li>
          <li><a class="nav-link scrollto" href="#contact">Contact</a></li>
          <li><a class="getstarted scrollto" href="#about">Get Started</a></li>
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->

  <main id="main">

    <!-- ======= Breadcrumbs ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <ol>
          <li><a href="index.html">Home</a></li>
          <li>Inner Page</li>
        </ol>
        <h2>Inner Page</h2>

      </div>
    </section><!-- End Breadcrumbs -->

    <section class="inner-page">
      <div class="container">
        <p>
          Example inner page template
        </p>
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12 text-center">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="index.html" class="logo d-flex align-items-center">
              <img src="assets/img/logo.png" alt="">
              <span>FlexStart</span>
            </a>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>FlexStart</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
  <script src="assets/vendor/aos/aos.js"></script>
  <script src="assets/vendor/php-email-form/validate.js"></script>
  <script src="assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="assets/vendor/purecounter/purecounter.js"></script>
  <script src="assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="assets/vendor/glightbox/js/glightbox.min.js"></script>

  <!-- Template Main JS File -->
  <script src="assets/js/main.js"></script>

</body>

</html>